
version: "3.8"
services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/postsharingdb
  mongodb:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
  mongo-express:
    image: mongo-express:latest
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
volumes:
  mongodb_data:
